// <auto-generated />
using A.MyAirport.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace A.MyAirport.EF.Migrations
{
    [DbContext(typeof(MyAirportContext))]
    [Migration("20200221150230_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("A.MyAirport.EF.Bagage", b =>
                {
                    b.Property<int>("BAGAGEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CLASSE")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("CODE_IATA")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("DATA_CREATION")
                        .HasColumnType("int");

                    b.Property<string>("DESTINATION")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("ESCALE")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool>("PRIORITAIRE")
                        .HasColumnType("bit");

                    b.Property<string>("SSUR")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("STA")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("VOLID")
                        .HasColumnType("int");

                    b.HasKey("BAGAGEID");

                    b.ToTable("Bagages");
                });

            modelBuilder.Entity("A.MyAirport.EF.Vol", b =>
                {
                    b.Property<int>("VOLID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CIE")
                        .HasColumnType("int");

                    b.Property<string>("DES")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("DHC")
                        .HasColumnType("int");

                    b.Property<string>("IMM")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("JEX")
                        .HasColumnType("int");

                    b.Property<string>("LIG")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("PAX")
                        .HasColumnType("int");

                    b.Property<string>("PKG")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("VOLID");

                    b.ToTable("Vols");
                });
#pragma warning restore 612, 618
        }
    }
}
