// <auto-generated />
using System;
using A.MyAirport.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace A.MyAirport.EF.Migrations
{
    [DbContext(typeof(MyAirportContext))]
    [Migration("20200224142838_changement")]
    partial class changement
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("A.MyAirport.EF.Bagage", b =>
                {
                    b.Property<int>("BAGAGEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CLASSE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CODE_IATA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DATA_CREATION")
                        .HasColumnType("datetime2");

                    b.Property<string>("DESTINATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESCALE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PRIORITAIRE")
                        .HasColumnType("bit");

                    b.Property<string>("SSUR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VOLID")
                        .HasColumnType("int");

                    b.HasKey("BAGAGEID");

                    b.HasIndex("VOLID");

                    b.ToTable("Bagages");
                });

            modelBuilder.Entity("A.MyAirport.EF.Vol", b =>
                {
                    b.Property<int>("VOLID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CIE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DHC")
                        .HasColumnType("datetime2");

                    b.Property<string>("IMM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("PAX")
                        .HasColumnType("smallint");

                    b.Property<string>("PKG")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VOLID");

                    b.ToTable("Vols");
                });

            modelBuilder.Entity("A.MyAirport.EF.Bagage", b =>
                {
                    b.HasOne("A.MyAirport.EF.Vol", "Vol")
                        .WithMany()
                        .HasForeignKey("VOLID");
                });
#pragma warning restore 612, 618
        }
    }
}
